### ISSUE TITLE
[iceworks] 3.x Beta Check List

### ISSUE THREAD

**Issue by chenbin92** [alibaba/ice#2228]
## 功能点

[PRs](https://github.com/alibaba/ice/pulls?q=is%3Aopen+is%3Apr+label%3A%22iceworks+3.0%22)

### 项目开发

- 面板
    - [x] 项目类型检测，非标项目给出提醒； @alvinhui https://github.com/alibaba/ice/pull/2273
    - [x] 面板设置的 UI 和交互优化； @chenbin92 https://github.com/alibaba/ice/pull/2212
    - [x] 添加「任务面板」 @chenbin92 
    - [x] 添加「引导面板」 @chenbin92 https://github.com/alibaba/ice/pull/2212
    - [x] Header 的图标提示统一用 Tooltip @boiawang https://github.com/alibaba/ice/pull/2239
    - [x] Panel 标题后统一加 Help @alvinhui 
    - [ ] 面板的滚动条定制
- 页面管理
    - [x] 新建页面和添加区块； @alvinhui  https://github.com/alibaba/ice/pull/2223
    - [x] 删除页面，同时删除路由和菜单； @boiawang 
- 菜单管理 @boiawang 
    - [x] 菜单管理新增顶部和侧边栏类型选择；https://github.com/alibaba/ice/pull/2205

### 工程管理

- [ ] Dev 启动日志添加进度条 

### 全局功能 @alvinhui 

- [x] 前台一些异步操作后的 UI 处理，如：安装依赖、DEF 发布；
- [ ] 前端异步请求前的等待效果，请求后的错误处理、无数据处理；

### 物料市场

- [ ] 物料里的组件需要显示「是否使用」

### Node 服务层 @Orange-C 

- [x] 多语言；
- [x] 日志分级和云端存储；

### Adapter 的多种实现
- [x] ice-script@1.x + pro@2x  @chenbin92 @temper357 
- [x] ice-script@2.x + pro@2x @chenbin92 @temper357 
- [x] ice-script@2.x + pro@3x @chenbin92 @temper357 
- [x] vue @Orange-C 

### Cli 版本 @chenbin92 

- [x] Cli Beta 版本的发布，及 Iceworks 发布流程的文档补充。
 
### 项目开发

**基础** @alvinhui 

* [x] 推荐模板丢失
* [x] 项目列表内的项目名称过长，需要做处理

**Git** @alvinhui 

* [x] 初始项目时终端控制台出现 git 相关错误
* [x] git 修改仓库地址后，再次修改状态没有刷新
* [x] git 点击切换分支无反应，服务端报错
* [x] git 提交成功需给出提示，以及无文件时的提示

**路由面板**

* [x] 创建路由报错信息没有显示 @boiawang 

**TODO 面板** @Orange-C 

* [x] 待办事项改为 TODO

**页面面板** @alvinhui 

* [x] 删除页面失败

**布局面板**

* [x] 布局新增一个刷新功能 @boiawang https://github.com/alibaba/ice/pull/2239

**OSS 面板** @alvinhui 

* [x] OSS 在内网不需要显示 https://github.com/alibaba/ice/pull/2238

### 工程管理  @temper357 

* [x] 运行状态在刷新页面后状态丢失 https://github.com/alibaba/ice/pull/2262
* [x] writeLog undefined  https://github.com/alibaba/ice/pull/2259
* [x] 项目没有 ice.config.js 时的处理  https://github.com/alibaba/ice/pull/2277

### 物料 @DoranYun

* [ ] 物料图片展示非常慢，需要优化
* [x] 添加物料的表单中对字段给出 tooltip 的提示
* [x] 删除物料源需要二次确认

### 设置 @Orange-C 

* [x] 刷新显示主题会抖动 https://github.com/alibaba/ice/pull/2232
* [x] 设置面版的中英文问题 https://github.com/alibaba/ice/pull/2232

### GlobalBar  @chenbin92 

* [x] 项目名称的长度控制 
* [x] 日志台需要关闭功能
* [x] 主题按钮的文案修改
* [x] 日志主题优化
* [ ] 编辑器打不开 

### 全局

* [x] 统一 check 表单内的 Help 图标 @boiawang 
* [x] Panel 的 Header 需抽象一个组件，不抽象将导致图标无法点击 @alvinhui

**Comment by alvinhui** [comment]
### 推荐模板丢失

![img](https://img.alicdn.com/tfs/TB1Ju5bdAWE3KVjSZSyXXXocXXa-2872-1588.png)

**Comment by alvinhui** [comment]
名称过长需要截断处理

![screenshot](https://img.alicdn.com/tfs/TB1Uia2dlGw3KVjSZFDXXXWEpXa-698-302.png)

**Comment by alvinhui** [comment]
## 样式和产品体验走查 Round 1

### 物料市场

- [ ] 物料类型（模板、区块、组件）选择项的宽度需更大，更可点击 @DoranYun 

### 项目开发

全局 @alvinhui 

- [ ] 没有项目时，隐藏右侧面板设置浮动入口 

引导面板 @chenbin92 

- [ ] 要有行动点，且进行高亮及可操作 

页面管理 @alvinhui 

- [ ] 新建页面时，如果项目内没有路由分组，则不显示路由分组选项

路由管理 @boiawang 

- [ ] 添加路由时，优化当前交互，透出路由分组概念，首先选择是分组路由还是普通路由。
- [ ] 路由列表，分组路由和普通路由的显示应有差别

### 工程管理 @chenbin92 

- [ ] 日志区块的高度需撑满

**Comment by chenbin92** [comment]
- [ ] 兼容 2.x 和 vue 的相关 adapter 开发 https://github.com/alibaba/ice/issues/2249

**Comment by chenbin92** [comment]
# TODO

## 文档
 iceworks 3.0 文档 https://github.com/alibaba/ice/pull/2247

**基础** @temper357 
- [ ] 迁移到 3.0 

**项目管理** @alvinhui  @boiawang 
  - [ ]  路由面板
  - [ ]  导航面板
  - [ ] Git 面板
  - [ ] OSS 面板
  - [ ] Mock 面板
  - [ ] 其他

**工程管理** @chenbin92 
- [ ] 调试服务
- [ ] 构建服务
- [ ]  语法检查
- [ ]  工程配置

**物料市场** @DoranYun 
 - [ ] 官方物料
 - [ ] 私有物料

## 官网
- [ ] iceworks 3.0 官网更新，设计稿：[Dark 版本](https://img.alicdn.com/tfs/TB1bURLeQ9E3KVjSZFGXXc19XXa-1915-4338.png)、[Light 版本](https://img.alicdn.com/tfs/TB1Re0PeSWD3KVjSZSgXXcCxVXa-1917-6842.png)

## 功能
- [ ] 服务端多语言翻译
- [ ] 数据埋点  https://github.com/alibaba/ice/issues/2026

## Bugs
- [ ] server依赖更新之后Configuration面板配置出现问题 https://github.com/alibaba/ice/issues/2269
- [ ] 工程面板增加 dev 报错信息 https://github.com/alibaba/ice/issues/2274

## 测试
- [ ] iceworks 兼容三个 Adapter 的测试，并补充文档：「迁移到」 3.0 章节
- [ ] 完成流程演示

**Comment by chenbin92** [comment]
# iceworks 功能演示说明

基于 iceworks/release-3.x 分支进行功能演示

## 项目管理  @alvinhui  @boiawang 
   - [ ] 创建项目、导入项目
   - [ ] 项目管理面板功能展示
        - [ ] 快速启动项目、构建项目
        - [ ] 页面列表（新建页面、删除页面）
        - [ ] 路由管理  @boiawang 
        - [ ] 菜单管理  @boiawang 
        - [ ] 依赖管理
        - [ ] Git  功能
        - [ ] OSS 功能
        - [ ] DEF  发布

## 工程管理 @chenbin92 
  - [ ] 启动调试服务，关闭调试服务，参数配置
  - [ ] 构建项目服务，关闭构建项目服务，参数配置
  - [ ] Eslint 检查
  - [ ] 配置修改

## 物料市场 
  - [ ] 展示物料相关的信息

## 设置 @chenbin92 
  - [ ] 语言切换
  - [ ] 主题切换
  - [ ] 编辑器
  - [ ] 文件夹

## 其他
- [ ] iceworks 兼容三个 react Adapter 的测试 @temper357 
- [ ] iceworks 兼容 vue Adapter 的测试 @Orange-C

**Comment by chenbin92** [comment]
# 问题记录:

## 创建项目 & 导入项目
1. 如果物料数据的模板没有配置 Adapter，项目面板的展示优化
2. 没有 Adapter 时的文档提示
3. 在代码添加 Adapter 时，iceworks UI 应该自动刷新
4. 选择不识别的 Adapter 项目前端没有适配

## 项目管理

@alvinhui 
1. dev 和 build 面板丢失
2. 页面列表排序跟编辑器保持一致
3. 创建页面的 title 国际化问题
4. 模板中 package.json 的 iceworks 字段中需要增加 type 字段，标记为 react 或者 vue
5.  [优化] 新建页面模态框优化
6. 搭建页面区块的 Edit 编辑图标可点
7. 搭建页面时同名的处理
8. 填写页面信息创建页面失败，以及样式问题 
9. 区块的 build 目录需要删除
10. 搭建区块生成的页面统一使用 index.jsx , 且改成 hooks
11. 页面可见就更新一下面板数据
12. 日志重复打印
13. [优化] 全局日志分操作日志和进程日志
14. 下载物料源失败透出 URL 地址
15. 切换分支之后推送代码失败
16. def 发布打印 log 失败
17. Git 本地存在分支有 bug
18. Git 切换分支隐藏
19. DEF 发布失败
20. 创建页面是 「确定」 按钮需要 disabled

@boiawang 
21. 删除导航提示优化
22. 创建菜单的 「名字」、「路径」统一添加 Tips
23. 创建菜单图标移不上去
24. 路由面板的飞机图标去掉
25. Header 部分的创建路由 iceworks 挂掉了 
26. 页面已存在后端服务报错，前端需要透出提示
27. 路由和菜单找不到文件时需要给出提示，菜单管理的操作按钮隐藏

## 工程管理  @chenbin92 
27. 清除 log 报错
28. 设置面板修改生效，但前端显示旧的
29. 日志台高度没撑满
30. dev start 点击按钮无法停止
31. 打开编辑器报错
32. 自定义配置没有读实时数据

## 物料 @DoranYun 

* 只有一个 「全部」 分类去掉
* 切换到物料面板 全局日志 换不起来

## Adapter

1. adapter-react-v1 控制台报错，getCliConf 报错

## 其他

1. 操作路径都写入 global 控制台
2. 国际化统一 check
3. dialog 统一宽度

**Comment by alvinhui** [comment]
## Check List

@temper357 

- [ ] 前端异步请求前的等待效果，请求后的错误处理、无数据处理；
- [ ] Adapter 里的 adapter-react-v1 控制台报错，getCliConf 报错 

@boiawang 

- [ ] 模板中 package.json 的 iceworks 字段中需要增加 type 字段，标记为 react 或者 vue。当创建页面时，只透出与项目相关的物料源：

    ```javascript
    {
        "iceworks": {
            "type": "react"
        }
    }
    ```
- [ ] 创建页面创建路由需要使用创建页面返回的 pageName，用于生成 router 内的代码
- [ ] 提供 react-v3 的物料源


@alvinhui 

- [ ] 创建项目时没有 Adapter 不应该有下载依赖的提醒
- [ ] 创建页面时，表单的样式问题
- [ ] 安装依赖时，日志重复打印

@Orange-C 

- [ ] vue 创建项目失败
- [ ] 编辑器打不开

## 优化点 

- [ ] 页面可见时就更新一下面板数据
- [ ] 下载物料失败透出 URL 地址

### 发布 beta 版本

7.8：

- [ ] 数据统计方案：https://github.com/alibaba/ice/pull/2318
- [ ] 发布 npm 版本的 beta 版本；@思忠
- [ ] 准备一篇使用文档，发布到语雀或者 wiki；@思忠
- [ ] 发推广消息到飞冰外部群，引导外部用户加飞冰 iceworks 3.0 体验群；

    - 创建群；@思忠
    - 发广告消息（iceman）：@梧忌

### 正式版本

7.18：

- [ ] [文档问题](https://github.com/alibaba/ice/pull/2247)：7.12 @及浩
- [ ] [站点问题](https://img.alicdn.com/tfs/TB1bURLeQ9E3KVjSZFGXXc19XXa-1915-4338.png)：7.15 @及浩
- [ ] Electron 版本：7.15 @梧忌

**Comment by chenbin92** [comment]
## Final Check

## 物料
- [ ] 提供 v3 的物料源地址，iceworks 3.0 默认内置 v3 物料源

## 功能走查
- [ ]  演示完整的流程

## 发布
- [ ] iceworks-client 、iceworks-server、iceworks-cli 分别发布对应的包，打 tag 
- [ ] 准备一篇简单的介绍文档，发布到  issue（方便大家讨论提交问题）
- [ ] 发推广消息到飞冰外部群，引导外部用户加飞冰 iceworks 3.0 体验群
   - [ ] 创建群
   - 发布消息（iceman）

**Comment by chenbin92** [comment]
iceworks 3.0 beta 版本已发布，目前在这里管理太混乱，未完成的任务已迁移到 https://github.com/alibaba/ice/projects/5 进行管理，按周迭代。
