### ISSUE TITLE
[iceworks]RFC: Adapter 开发规范讨论

### ISSUE THREAD

**Issue by chenbin92** [alibaba/ice#2249]
## 名词解释

Adapter, iceworks 为了适配不同工程工具以及不同项目结构而抽象出的概念，Adapter 核心会实现两部分能力：

1. 工程工具：即使用的构建调试工具，比如 ice-scripts/vue-cli，决定了项目启动构建以及工程配置等能力
2. Kit: 即项目开发的最佳实践，包含目录结构、路由配置、权限管理等，决定了面板里新建页面、新建路由如何实现，目前有两个版本 Kit@2.x（routeConfig/menuConfig）Kit@3.x（配置信息收敛到 config/）

## 项目约定

通过对项目指定对应的 adapter 即可接入 iceworks 进行开发，配置如下：

```json
// 用户项目的 package.json
{
  "iceworks": {
    "adapter": "ice-adapter",   
  }
}
```

### 加载时机

当用户在 iceworks 「切换项目」、「导入项目」、「新建项目』时，需要根据项目的 `package.json` 中指定的 `adapter` 进行动态安装并进行加载。

* adapter 在 iceworks 运行环境中执行，因此会作为 iceworks 的依赖进行安装。
* adapter 的版本策略
* adapter 检查更新机制
* 检查当前 adapter 是否已经安装

### 加载逻辑

当检测到项目变化时需要发送请求到后端，并检查当前 adapter 是否已经安装过：
* 如果已经安装过的 adapter 则会写入到 用户系统 `.iceworks` 的配文件中进行缓存，以此保证不必要的安装流程。
* 如果检查当前 adapter 没有安装，则需要动态执行安装 adapter 的操作，当安装完成时，并重新执行 loadAdapter 方法进行初始化。在安装过程中前端 UI 需要给出对应的提示，告知用户「由于当前项目依赖的 Adapter 发生改变，正在重新加载」 之类的提示。

![加载逻辑](https://img.alicdn.com/tfs/TB1Dn_NaMFY.1VjSZFqXXadbXXa-2246-1464.png)

## 面板开发

* 面板 UI  配置

面板 UI 配置指的是在 iceworks 中 「项目管理」和「工程管理」的面板展示形式可被修改，被定制成根据 Adapter 的实现进行展示的一种机制。其核心实现是面板 UI 部分会提供对应的属性，通过在 Adapter 中配置属性进行面板的配置化展示。

* 隐藏面板

隐藏面板指的是在 iceworks 中「项目管理」和「工程管理」的面板展示可被隐藏，可以根据实际工程的最佳实践只展示某些需要的面板。其核心实现是 Adapter 开发中只实现需要展示的面板接口即可，未实现的接口则不会进行展示。

* 新增面板（暂不实现）

新增面板指的是在 iceworks 中「项目管理」和「工程管理」的面板展示上新增加一个面板，或者当面板 UI 定制提供的属性不能满足定制需求时，需要进行面板开发。

### Adapter 目录规范

```
adapter
├─ modules/         ---- 模块实现
│  ├─ menu/
│  ├─ router/ 
│  ├─ task/ 
│  └─ index.ts
|
├─ locales/         ---- 多语言配置
│  ├─ en-US.json
│  └─ zh-CN.json
|
├─ package.json
└─ README.md
```

### Adapter 开发

* 如果你需要实现的 Adapter 功能与 ICE 团队提供的 Adapter 功能大致相似，但是你希望定制面板 UI 或者想隐藏一些面板时，我们希望你基于 ice adapter 进行开发。

**面板逻辑实现**
```ts
// adapter/modules/menu.ts
// Menu 实现
import * as iceAdapter from '../ice-adapter';

class MenuAdapter extends iceAdapter.Menu {
  getAll() {

  }
}
```

**面板 UI 配置**
```ts
// config.ts
const config = {
 menu: {
    title: '菜单管理',
    description: '展示项目中的所有菜单，支持对菜单的增删改。',
    cover: 'https://img.alicdn.com/tfs/TB1mZ.Xc8GE3KVjSZFhXXckaFXa-300-300.png',
    isAvailable: true,

    // 新增 props 字段，用于控制前端 UI 面板的展示
    props: {
      icon: 'home',
    } 
  },
}
```

**Adapter 面板导出**
```ts
// index.ts
import Menu from './menu';

export {
  menu: {
      title: '',
      description: '',
      cover: ''
      module: Menu,
      isAvailable: true
  },
  ...
};

```

* 如果你需要实现的 Adapter 功能与 ICE  团队提供的 Adapter 功能差异较大，你可以根据 **接口定义** 单独实现 Adapter 功能，以及新增面板功能等。

注释：暂不支持

## 关于 Adapter 命名规范

命名规范遵循 「简单」、「语义化」、「易理解」原则，Adapter 命名规范如下：

``` md
# 命名规范
=> adapter-<工程工具名称>-<工程工具版本>-<最佳实践模板名称>-<最佳实践模板版本>

# 命名示例
=> adapter-ice-scripts-2-kit-2
=> adapter-ice-scripts-2-kit-3
```

## TODO
- [x] 动态加载的能力  @chenbin92   
- [x] 目录改造 @chenbin92   
- [ ] props 定制面板能力 @temper357 
- [ ] ice-script@1.x + kit@2x  => adapter-ice-scripts-1-kit-2  @temper357 
- [ ] ice-script@2.x + kit@2x  => adapter-ice-scripts-2-kit-2 @temper357  
-  [ ] ice-script@2.x + kit@3x => adapter-ice-scripts-2-kit-3  @chenbin92   
- [ ] vue-cli@3.x + kit@2x => adapter-vue-cli-3-kit-2 @Orange-C 
- [ ] 老项目迁移到 3.x 给出引导提示 @chenbin92 

## 其他
- 涉及到目录改动，对现有 iceworks-3.x 的变更可能会有冲突

**Comment by chenbin92** [comment]
> # 命名规范
> => adapter-<工程工具名称>-<工程工具版本>-<最佳实践模板名称>-<最佳实践模板版本>
> # 命名示例
> => adapter-ice-scripts-2-kit-2
> => adapter-ice-scripts-2-kit-3

针对上述命名规范，@yuanyan 提出了不同的看法和建议，主要有以下几点考虑：

* `adapter-ice-scripts-2-kit-2` 命名太不优雅，2 最起码也应该用 v2 表示，同时在软件架构中，如需必要，勿新增实体
* `kit` 代表的是项目的最佳实践，ice-scripts 代表的是对应的工程工具，思考背后其实应该是 kit 是包含 ice-scripts 的的关系，是可以根据 kit 推导出对应的工程 ice-scripts 版本的，因此命名也应该是 `adapter-kit-v3-ice-scripts-v2`
* 第二点讨论到可以根据 kit 是可以推导 ice-scripts 的版本的，因此可以不必显示的声明 ice-scripts 实体和版本，因此命名可以进一步优化为 `adapter-kit-v3`
* ice 项目的最佳实践和工程实践可以定位为 React 生态下的最佳实践，因此可以考虑将包名命名为 `react-adapter`，最终形态如下：

 ice-script@1.x + kit@2x => adapter-ice-scripts-1-kit-2 
  ice-script@2.x + kit@2x => adapter-ice-scripts-2-kit-2
  ice-script@2.x + kit@3x => adapter-ice-scripts-2-kit-3

```
react-adapter
├── kit-v2 # 对应  ice-script@1.x + kit@2x 和 ice-script@2.x + kit@2x，考虑两者都是兼容方案，可以合并为一个，也可以减少多个 adapter 的维护成本
└── kit-v3 # 对应 ice-script@2.x + kit@3x ，接下来主推的套件
```

### 项目配置

```
iceworks: {
   adapter:  react-adapter-kit-v2 # or react-adapter-kit-v3
}
```

**Comment by Orange-C** [comment]
如果能把原来cli和kit二维的diff合并成为kit的diff，我觉得这个命名可以

**Comment by boiawang** [comment]
> 第二点讨论到可以根据 kit 是可以推导 ice-scripts 的版本的，因此可以不必显示的声明 ice-scripts 实体和版本，因此命名可以进一步优化为 adapter-kit-v3

如何通过 kit 检测？

> ![image](https://user-images.githubusercontent.com/6340730/60148905-65b30400-9805-11e9-9a56-f8a42c979744.png)

如何从 `react-adapter-kit-v2` 推演出 `react-adapter/kit-v2`

**Comment by chenbin92** [comment]
> 如果能把原来cli和kit二维的diff合并成为kit的diff，我觉得这个命名可以

`原来cli和kit二维的diff合并成为kit的diff` 没理解你说的这个是什么意思

**Comment by chenbin92** [comment]
> > 第二点讨论到可以根据 kit 是可以推导 ice-scripts 的版本的，因此可以不必显示的声明 ice-scripts 实体和版本，因此命名可以进一步优化为 adapter-kit-v3
> 
> 如何通过 kit 检测？
> 
> > ![image](https://user-images.githubusercontent.com/6340730/60148905-65b30400-9805-11e9-9a56-f8a42c979744.png)
> 
> 如何从 `react-adapter-kit-v2` 推演出 `react-adapter/kit-v2`

可以读取项目 package.json 中 devDependencies 的 ice-scripts 版本

**Comment by boiawang** [comment]
```
iceworks: {
   adapter:  react-adapter/kit-v2 # or react-adapter/kit-v3
}
```

**Comment by chenbin92** [comment]
> `package.json` 里这样写是不是更好？
> 
> ```
> iceworks: {
>    adapter:  react-adapter/kit-v2 # or react-adapter/kit-v3
> }
> ```

为什么这样好，理由是什么

**Comment by boiawang** [comment]
> > `package.json` 里这样写是不是更好？
> > ```
> > iceworks: {
> >    adapter:  react-adapter/kit-v2 # or react-adapter/kit-v3
> > }
> > ```
> 
> 为什么这样好，理由是什么

命名更加直观，命名规范 `npmName/dirName` 比 xxx-adapter-xxx-v3(npmName-dirName) 理解成本更小一点

**Comment by temper357** [comment]
未来不同kit版本的adapter会不会单独发npm包? packages.json中名字是不是和包名统一就行了

**Comment by chenbin92** [comment]
> 未来不同kit版本的adapter会不会单独发npm包? packages.json中名字是不是和包名统一就行了

+1 我是支持发 Npm 包的

**Comment by boiawang** [comment]
> > 未来不同kit版本的adapter会不会单独发npm包? packages.json中名字是不是和包名统一就行了
> 
> +1 不同的 Kit 版本单独发 Npm 包

昨天 @yuanyan 的意思应该是只有 `react-adapter` 一个 npm 包，不同的 Kit 版本都放在这个 npm 下

**Comment by imsobear** [comment]
先明确概念：

- Adapter: 包含工程和项目开发最佳实践两部分
- 工程：开发调试+构建，如 ice-scripts，目前有两个版本 1.x（buildConfig）2.x（ice.config.js）
- 项目开发最佳实践：Kit，包含目录结构、路由配置协议、菜单配置协议等，目前有两个版本 2.x(routeConfig.js) 3.x(config/routes.js)

Kit 的概念是否应该包含工程+项目开发最佳实践？我认为不应该，因为 Adapter 本身表达的就是这个意思，没必要再搞一个同类型的概念，同时工程的演进和项目开发最佳实践是相互独立演进的，基本没有耦合关系。

-------

```
react-adapter
├── kit-v2 # 对应  ice-script@1.x + 目录结构@2x 和 ice-script@2.x + 目录结构@2x，考虑两者都是兼容方案，可以合并为一个，也可以减少多个 adapter 的维护成本
└── kit-v3 # 对应 ice-script@2.x + 目录结构@3x ，接下来主推的套件
```

这个方案最大的问题是：为什么工程版本变化了是在一个 adapter 里兼容，而目录结构变化了却是新起一个 adapter？一方面规则很奇怪，另一方面 adaper 的实现也要考虑工程兼容。

因此我认为无论是工程还是目录结构发生 break change 都应该新起一个 adapter。

然后回到 adapter 命名的问题，两种方案我自己都可以接受：

1. `adapter-ice-scripts-2-kit-2`：缺点是命名太长，不优雅，优势是表达的意思非常明确，不需要用户做进一步理解
2. `adapter-react-v1`，优缺点刚好相反，需要有一份文档告知用户映射关系：

|     adatper         |   ice-scripts |     kit      |
|--------------    |------------ |---------|
|adapter-react-v1|   1.x             |      2.x     |
|adapter-react-v2|   2.x             |     2.x     |
|adapter-react-v3|   2.x             |     3.x     |

**Comment by alvinhui** [comment]
方案二 +1

**Comment by boiawang** [comment]
方案二+2

**Comment by Orange-C** [comment]
如果工程和kit的确是非常独立的话，映射表应该是这样的

script/kit| V1 | V2 | V3
-----|------- | -------|------
V1 |  / |  adapterV1 | /
V2 | /  |  adapterV2 | adapterV3

两者必须要有联系和约束，比如工程会支持kit的版本有限制，不然未来可能是这样

script/kit| V1 | V2 | V3 | V4 | V5
-----|------- | -------|------ |------ |------
V1 |  / |  adapterV1 | / | / | / |
V2 | /  |  adapterV2 | adapterV3 | adapterV4 | adapterV5
V3 | /  |  / | adapterV6  | adapterV7  | adapterV8

基于这个考虑，我的想法是：

1. 使用方案二，但是要声明工程和kit同时使用的规则
2. 使用方案一

**Comment by chenbin92** [comment]
> 如果工程和kit的确是非常独立的话，映射表应该是这样的
> 
> script/kit	V1	V2	V3
> V1	/	adapterV1	/
> V2	/	adapterV2	adapterV3
> 两者必须要有联系和约束，比如工程会支持kit的版本有限制，不然未来可能是这样
> 
> script/kit	V1	V2	V3	V4	V5
> V1	/	adapterV1	/	/	/
> V2	/	adapterV2	adapterV3	adapterV4	adapterV5
> V3	/	/	adapterV6	adapterV7	adapterV8
> 基于这个考虑，我的想法是：
> 
> 1. 使用方案二，但是要声明工程和kit同时使用的规则
> 2. 使用方案一

第二种映射表没有这么复杂，就是 `adapter = 工程版本 + kit 版本` 约束一下就行了

**Comment by temper357** [comment]
方案二 +1

**Comment by Orange-C** [comment]
> 第二种映射表没有这么复杂，就是 `adapter = 工程版本 + kit 版本` 约束一下就行了

那不就是有V2 +V3 和V3 + V2一样的问题了，或者说有一条规则，工程版本不会低于kit版本？

我们把这些规则都说清楚了，那方案二是没啥问题的，

**Comment by chenbin92** [comment]
## 关于 Adapter 集成问题的讨论

目前在实际开发中，`adapter-react-v1` 、 `adapter-react-v2`、`adapter-vue-v1` 都会继承自 `adapter-react-v3`，可能会出现以下问题：

* 问题一：继承关系链不语义
```
import AdapterV3 from 'adapter-react-v3';

class Menu extends from AdapterV3.Menu {
  // 定制逻辑
}
```

* 问题二：如果 v3 的实现发生改变，对应的集成关系链都将受到影响，本质上是把 v3 当做了 adapter 基类进行了继承

* 问题三：在未来一段时间，如果我们的 kit 或者是工程发生改变时，需要推出 `adapter-react-v4` 版本，但仍然有部分功能可以基于 `adapter-react-v3` 进行复用，那么此时是否还要基于 v3 进行继承，这显然不合理

## 综上：

考虑基于现有 v3 进行抽象设计一个 adapter 基类，其他 adapter 的实现都基于该 adapter 基类进行继承，可解决上述问题。

```js
import Adapter from 'Adapter';

// 基于基类定制 Menu 的 v1 版本
class MenuV1 from Adapter.Menu {

}

// 基于基类定制 Menu 的 v2 版本
class MenuV2 from Adapter.Menu {

}

// 基于基类定制 Menu 的 v3 版本
class MenuV3 from Adapter.Menu {

}
```

**Comment by Orange-C** [comment]
## vue-adapter需求点

1. 大部分逻辑不需要改动，可以支持大到整个adapter，小到module级别的继承
2. 只需要改动`configuration`, `task`的 confFileName 以及 const文件即可使用这两个面板，可以支持直接这两个配置的覆盖式继承

**Comment by chenbin92** [comment]
> 2. const

+1

把 const 挂载到 this 上面吧，直接来个 MR

**Comment by chenbin92** [comment]
> ## vue-adapter需求点
> 1. 大部分逻辑不需要改动，可以支持大到整个adapter，小到module级别的继承
> 2. 只需要改动`configuration`, `task`的 confFileName 以及 const文件即可使用这两个面板，可以支持直接这两个配置的覆盖式继承

+1

把 const 挂载到 this 上面吧，直接来个 MR

**Comment by alvinhui** [comment]
> ```js
> class MenuV1 from Adapter.Menu.module {
> ```

`class MenuV1 from Adapter.Menu.module ` 这样写感觉很奇怪。
看一下 Adapter 导出那里怎么处理更合适。
Adapter 的导出还需要考虑面板控制显示隐藏的逻辑：https://github.com/alibaba/ice/blob/4ea49fa6e4e21d16d47c73d319468edfebc98ea0/packages/iceworks-server/src/lib/adapter/getPanels.ts

**Comment by temper357** [comment]
刚刚 @boiawang 反馈了一个问题，kit 1.0没有对应的adapter，我重新思考了一下ice-scripts与adapter的关系，目前ice-scripts 1.0与ice-scripts 2.0对于adapte的唯一影响就是1.0少了Configuration模块，但是目前iceworks的client已经对ice.config.js取不到的情况作了兼容，取不到就不展示设置面板。所以当前的v1和v2其实完全可以配置成一样的，由此推导出adapter其实只和kit的版本有关系，对应可以重新梳理为：

|     adatper         |       kit      |
|--------------    |----------|
|adapter-react-v1|       1.x     |
|adapter-react-v2|      2.x     |
|adapter-react-v3|       3.x     |

**Comment by temper357** [comment]
最新adapter对应关系如下：

# iceworks@3.0

- icekit@1.x: routerConfig.js，扁平并且有 layout 字段
- icekit@2.x: routerConfig.js，children 
- icekit@3.x: config/routes.js, children

## adapter-react-*

> ice-scripts+icekit

v0: ice-scripts@1.x icekit@1.x  存量
v1: ice-scripts@2.x icekit@1.x  存量
v2: ice-scripts@2.x icekit@2.x  即将存量
v3: ice-scripts@2.x icekit@3.x  coming

## adapter-vue-*

> vue-cli+icekit

v1: vue-cli@current icekit@1.x  存量
v2: vue-cli@current icekit@3.x  coming

## adapter-cra-*

> create-react-app+icekit

v1: create-react-app@current icekit@3.x comming

# iceworks 2.0

- 兼容 icekit 1.0 和 2.0
