### ISSUE TITLE
icestark 发布

### ISSUE THREAD

**Issue by daysai** [alibaba/ice#2270]
## TODO

- [x] 基于 icekit3.0 完成两个模板
  - [x] 主应用模板，暂时 UI 上可以弱一点，等 fusion 的 shell 组件发布后按照规范升级整体 UI
  - [x] 子应用模板 UI 简化
- [x] 官方文档 Review & 发布
- [x] stark-router 合并发布
- [ ] 运营文章
