### ISSUE TITLE
基础能力升级

### ISSUE THREAD

**Issue by chenbin92** [alibaba/ice#3748]
## TODO

- [x] build-plugin-rax-app 和 build-plugin-react-app 怎么共享底层，从 build-plugin-app-base 扩展出来 @chenbin92 @SoloJiang 
- [ ] 将原有 create-cli-utils 能力从 build-scripts 提供  @luhc228 @chenbin92 
- [ ] 将原有 build-plugin-app-core 进行 generator 设计 @SoloJiang @chenbin92 
- [ ] document 能力

**Comment by SoloJiang** [comment]
https://github.com/alibaba/ice/issues/3752

**Comment by luhc228** [comment]
将原有 create-cli-utils 能力从 build-scripts 提供，包括下面几个功能：
- [ ] start 
- [ ] build 
- [ ] test
- [ ] childProcessStart
- [ ] createCli

**Comment by chenbin92** [comment]
##  工程改造

### `build-webpack-config` 

定位为工程的基础配置工具包，支持 rax-app（build-plugin-rax-app） 和 icejs（build-plugin-react-app）。提供如下接口：

- `registerCliOption`：注册 CLI 构建参数
- `registerUserConfig`：注册默认的用户配置
- `setDevConfig`：提供默认的 Dev 配置
- `setBuildConfig`：提供默认的 Build 配置
- `setTestConfig`：提供默认的 Test 配置
- `constants`: 提供一些基础的常量

### `build-plugin-rax-app` 

定位为 rax-app 工程插件，基于 build-plugin-app-base 进行自定义扩展，最终被 rax-app 依赖消费。

```js
import { registerCliOption、registerUserConfig、getDevConfig、getBuildConfig、getTestConfig } from '';

module.exports = (api) => {
  // register cli option
  registerCliOption(api);

  // register user config
  registerUserConfig(api);

  if (command === 'test') {
    setTest(api);
  }

  if (command === 'start') {
    setDev(api);
  }

  if (command === 'build') {
    setBuild(api);
  }
};
```

### `build-plugin-react-app` 

定位为 icejs 工程插件，基于 build-plugin-app-base 进行自定义扩展，最终被 icejs 依赖消费。

**Comment by chenbin92** [comment]
@SoloJiang @imsobear @ClarkXia  看下上述工程设计是否合理。

**Comment by SoloJiang** [comment]
## build-plugin-app-core 拆分

### build-webpack-config

- [ ] 设置项目类型
- [ ] 注册框架默认内置方法

### build-plugin-rax-app

- [ ] 基础 alias
- [ ] 设置 entry
- [ ] 注册框架自身内置变量，例如 TEMP_PATH

### build-app-generators

提供生成 `.rax/.ice` 临时目录文件的基础能力

```js
import { generateFile, generateCommonFiles } from 'build-app-generators';

// generateCommonFiles 生成默认的公共文件
generateCommonFiles('rax');

// generateFile 在 .rax 下任意生成某个文件
generateFile(templatePath, targetPath, { renderData });
```

**Comment by chenbin92** [comment]
确实现有 app-core runtime 的 API 逻辑

**Comment by imsobear** [comment]
> @SoloJiang @imsobear @ClarkXia 看下上述工程设计是否合理。

底层依赖数要控制下？比如 node-sass、typescript 不建议放到 build-webpack-config

**Comment by chenbin92** [comment]
@ClarkXia @SoloJiang  `registerCliOption` 和 `registerUserConfig` 改为 `applyCliOptions` 和 `applyUserConfig`

**Comment by chenbin92** [comment]
> ## 目标（CheckList）
> 将原有 create-cli-utils 能力从 build-scripts 提供，需要包括下面几个功能：
> 
> * [ ]  start
> * [ ]  build
> * [ ]  test
> * [ ]  childProcessStart
> * [ ]  createCli
> 
> ## 改造方案
> ### build-scripts 改造
> 1. 默认导出的 api 新增 `createCli` 和 `childProcessStart` ，分别对应 `src/commands/create-cli.ts` 和 `src/commands/child-process-start.ts`
> 2. `src/commands/start.ts` 、`src/commands/build.ts`、`src/commands/test.ts` 的参数获取不再从外部传入，相关逻辑直接在方法中，比如在 `build.ts`中：
>    ```diff
>    export = async function({
>      args,
>      rootDir,
>      eject,
>      plugins,
>      getBuiltInPlugins,
>    }: {
>    -   args: CommandArgs,
>    -   rootDir: string;
>    +  args?: CommandArgs,
>    +  rootDir?: string;
>        eject?: boolean;
>        plugins?: IPluginList;
>        getBuiltInPlugins?: IGetBuiltInPlugins;
>    }): Promise<void | ITaskConfig []> {
>    
>    + if (!args) {
>    +  const rawArgv = parse(process.argv.slice(2), {
>    +    configuration: { 'strip-dashed': true },
>    +  });
>    +  // ignore _ in rawArgv
>    +  delete rawArgv._;
>    +  args = { ...rawArgv };
>    + } 
>      
>      const context = new Context({
>        args,
>        command,
>        rootDir,
>        plugins,
>        getBuiltInPlugins,
>      });
>    }
>    ```
> 3. `bin/build-scripts.js` 改造：原有的逻辑与 `createCli` API 的逻辑大部分一致，因此直接调用 `createCli` API:
>    ```js
>    const createCli = require('../lib/commands/create-cli');
>    
>    (function () {
>      createCli()
>    })()
>    ```
> 4. 删除 `/bin` 目录下的 `build.js`、 `child-process-start.js` 、`start.js`、` test.js`
> 
> ### icejs & rax-app 改造
> 使用 `build-scripts` 能力代替 `create-cli-utils`：
> 
> ```diff
> - const utils = require('create-cli-utils');
> + const utils = require('@alib/build-scripts');
>   const getBuiltInPlugins = require('../lib/getBuiltInPlugins');
> 
>   (async() => {
>     await utils.childProcessStart(getBuiltInPlugins);
>   })();
> ```

1. 将现有 create-cli-utils 的逻辑放到 build-scripts 中
2. 将 build-scripts 中 bin 文件改为引用 create-cli-utils 移到 build-scripts 中的逻辑
3. rax-app 和 icejs 复用 create-cli-utils 移到 build-scripts 中的逻辑

**Comment by ClarkXia** [comment]
generator 设计在 https://github.com/alibaba/ice/issues/3878 中跟进
