### ISSUE TITLE
ice.js 2.0.0 版本进度

### ISSUE THREAD

**Issue by ClarkXia** [alibaba/ice#4458]
## 2.0.0 规划

- prebuild dependencies
- upgrade webpack 5
- support swc and esbuild by default
- built-in module federation for development
- runtime refactoring
- dependencies upgrade
- support vite: https://github.com/alibaba/ice/issues/4495

PR：https://github.com/alibaba/ice/pull/4334

## 使用 2.0.0 版本

```diff
{
- ice.js: "^1.0.0",
+ ice.js: "next"
}
```

## 问题记录

- [x] #4479
- [x] swc 首次安装速度偏慢 (swc 会自动根据系统信息下载对应编译包，暂不考虑预编译)
![image](https://user-images.githubusercontent.com/4219965/126736638-f80f3ae3-4262-41bc-81da-2ac29c6291bc.png)
- [x] swc 开启后，store 逻辑无法使用 @luhc228 #4501 
- [x] 构建时压缩使用 terser 报错 https://github.com/alibaba/ice/pull/4466
- [x] remoteRuntime 能力失效 https://github.com/alibaba/ice/pull/4467
- [x] 升级 react-dev-utils 工具集
- [x] webpack-dev-server 使用 4.x （目前为 next tag）#4478
- [x] mpa 场景下 babel 信息输出修正 @SoloJiang 
![image](https://user-images.githubusercontent.com/4219965/126598795-d39cbb63-1998-4a9d-9e4e-16c28e06ac20.png)
- [x] eslint 依赖内置
- [x] node 端 require.resolve 包含 exports 字段的包会有问题 [code](https://github.com/alibaba/ice/blob/release/2.0.0/packages/plugin-react-app/src/userConfig/remoteRuntime/writeRemoteFile.ts#L30) #4508
- [x] runtime 引入地址统一成相对地址 @SoloJiang 
- [x] peerDependencies WARNING 梳理，由于 webpack 预打包，导致一些依赖输出 peerDependencies WARNING 信息，尽可能减少类似的日志输出，提升安装体验
- [x] minify 字段能力梳理
- [x] exports 字段解析错误
- [x] store 场景下编译出现两次 @luhc228 
- [ ] swc plugin for babel-plugin-import @SoloJiang
